### ISSUE TITLE
Missing src directory?

### ISSUE THREAD

**Issue by a-v-s** [cpq/mdk#12]
It seems the source was removed in commit
34cee38a9c6b349ff34a91dc9aa30c05049ad2e7

02340055a16472e60f8ee1f1185fde20b2d3c387
seems to be the latest with the src directory,
all later commits on the main branch have
the src directory missing.

**Comment by cpq** [comment]
Well, that's how it should be. the `esp32` and `esp32c3` directories have all respective sources required. That's why "single-header" in the title.

**Comment by a-v-s** [comment]
Thanks, I now see how it works.
