### ISSUE TITLE
Please consider removing Docker

### ISSUE THREAD

**Issue by stacksmith** [cpq/mdk#16]
There is no reason to complicate the system, and some people _really_ don't want docker on their system.

Making the Espressif toolchain visible is trivial using their export script.  If you want you can check for it in mdk/tools/export.sh and prompt the user if it's not visible.

How the toolchain is maintained should be up to the user anywa y - you can use docker outside the mdk perimetert...   I think keeping it clean is a win (for instance, I removed a few lines with docker references,  but now I will have endless headaches merging your updates!).

Thanks.

**Comment by adriangrigore** [comment]
On `OpenBSD` I can actually install the toolchain via `pkg_add`.

**Comment by cpq** [comment]
@stacksmith could you suggest instructions on how to install gcc-riscv toolchain for windows, mac & linux?

**Comment by bartgrantham** [comment]
> Making the Espressif toolchain visible is trivial using their export script. If you want you can check for it in mdk/tools/export.sh and prompt the user if it's not visible.

Isn't the point of this repo to avoid Espressif's toolchain?

I find that having the toolchain in a docker image is _much_ nicer than having to install it locally.  It keeps things cleaner and is portable.

So please do not remove Docker.  But if you do, please keep the Dockerfile in the repo and maintain it as an option, it's a great way to simplify and overcome friction for people getting started.

**Comment by cpq** [comment]
It is easy to bypass docker and use a locally installed toolchain:

```sh
$ make -C examples/blinky/ ARCH=esp32c3 DOCKER=
riscv-none-elf-gcc  -W -Wall -Wextra ....
```
